title: Tech & Life
author: Shubh

remote_theme: pages-themes/hacker@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

# URL settings
url: "https://beshubh.github.io"
baseurl: "/writings" # the subpath of your site
