title: Shubh's Writings
theme: minima

# URL settings
url: "https://alias-pyking.github.io"
baseurl: "/writings" # the subpath of your site

# Permalinks
permalink: /:categories/:year/:month/:day/:title/

# Markdown settings
markdown: kramdown

# Custom collections
collections:
  tech:
    output: true
    permalink: /:collection/:name/
  life:
    output: true
    permalink: /:collection/:name/
